### PR TITLE
Support helm 3

### PR DESCRIPTION
**Pull request by rbren**
I'm not sure why the lines I changed from `exit 1` to `continue` ever worked - any ideas there?

### CODE REVIEW

**Comment by rbren** [comment]
Oh wait - now I'm seeing `helm 3` in the readme...very confused

**Comment by rbren** [comment]
Looks like the other helm 3 change just got rid of `--purge` flags. But I think the output of `helm ls` changed - at least the current `awk` commands don't work on my machine.

I can get rid of the version checking though

**Comment by hopson** [comment]
> I'm not sure why the lines I changed from `exit 1` to `continue` ever worked - any ideas there?

It looks like the previous version applied `$release_filter` on the initial helm command, so this was a sanity check.

**Comment by rbren** [comment]
Good catch Robert!

I removed the `did not match` logs, since that's no longer surprising. Also removed the helm version checking.

**Comment by rbren** [comment]
Thanks! Once this gets tagged/released I can make a PR on charts to update the version

**Comment by hopson** [comment]
Can you push a tag to this repo? I think that's all that's needed.

**Pull request merged**
